"""empty message

Revision ID: 3c05315d5b9b
Revises: f87909a4293b
Create Date: 2025-09-05 09:48:08.561045

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c05315d5b9b"
down_revision = "f87909a4293b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timeout", sa.Boolean(), nullable=False, server_default="false"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.drop_column("timeout")

    # ### end Alembic commands ###
