"""empty message

Revision ID: f87909a4293b
Revises: f04407e8e466
Create Date: 2025-09-03 16:36:14.608372

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f87909a4293b"
down_revision = "f04407e8e466"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_log")
    op.execute("DELETE FROM log")

    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service_id", sa.Integer(), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(sa.Column("ping", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_log_dateCreated"), ["dateCreated"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_log2service", "service", ["service_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("log", schema=None) as batch_op:
        batch_op.drop_constraint("fk_log2service", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_log_dateCreated"))
        batch_op.drop_column("ping")
        batch_op.drop_column("service_id")

    # ### end Alembic commands ###
